<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130821153857 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE lelesys_plugin_news_domain_model_folder (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_category ADD folder VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_category ADD CONSTRAINT FK_1E9D5950ECA209CD FOREIGN KEY (folder) REFERENCES lelesys_plugin_news_domain_model_folder (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_1E9D5950ECA209CD ON lelesys_plugin_news_domain_model_category (folder)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news ADD folder VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news ADD CONSTRAINT FK_C7BAC715ECA209CD FOREIGN KEY (folder) REFERENCES lelesys_plugin_news_domain_model_folder (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_C7BAC715ECA209CD ON lelesys_plugin_news_domain_model_news (folder)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_category DROP FOREIGN KEY FK_1E9D5950ECA209CD");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP FOREIGN KEY FK_C7BAC715ECA209CD");
		$this->addSql("CREATE TABLE lelesys_captcha_domain_model_captcha (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("DROP INDEX IDX_1E9D5950ECA209CD ON lelesys_plugin_news_domain_model_category");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_category DROP folder");
		$this->addSql("DROP INDEX IDX_C7BAC715ECA209CD ON lelesys_plugin_news_domain_model_news");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP folder");
	}
}

?>