<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130904173433 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE lelesys_plugin_news_domain_model_rating (persistence_object_identifier VARCHAR(40) NOT NULL, news VARCHAR(40) DEFAULT NULL, points INT DEFAULT NULL, INDEX IDX_D9543BF81DD39950 (news), PRIMARY KEY(persistence_object_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_rating ADD CONSTRAINT FK_D9543BF81DD39950 FOREIGN KEY (news) REFERENCES lelesys_plugin_news_domain_model_news (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		$this->addSql("DROP TABLE lelesys_plugin_news_domain_model_rating");
	}
}

?>