<?php

namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130823112619 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset ADD thumbnailresource VARCHAR(40) DEFAULT NULL, ADD iconresource VARCHAR(40) DEFAULT NULL, ADD carouselresource VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset ADD CONSTRAINT FK_4C3861DEA7D7E12 FOREIGN KEY (thumbnailresource) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset ADD CONSTRAINT FK_4C3861D6AE64E7B FOREIGN KEY (iconresource) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset ADD CONSTRAINT FK_4C3861DAA76C045 FOREIGN KEY (carouselresource) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_4C3861DEA7D7E12 ON lelesys_plugin_news_domain_model_asset (thumbnailresource)");
		$this->addSql("CREATE INDEX IDX_4C3861D6AE64E7B ON lelesys_plugin_news_domain_model_asset (iconresource)");
		$this->addSql("CREATE INDEX IDX_4C3861DAA76C045 ON lelesys_plugin_news_domain_model_asset (carouselresource)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset DROP FOREIGN KEY FK_4C3861DEA7D7E12");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset DROP FOREIGN KEY FK_4C3861D6AE64E7B");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset DROP FOREIGN KEY FK_4C3861DAA76C045");
		$this->addSql("DROP INDEX IDX_4C3861DEA7D7E12 ON lelesys_plugin_news_domain_model_asset");
		$this->addSql("DROP INDEX IDX_4C3861D6AE64E7B ON lelesys_plugin_news_domain_model_asset");
		$this->addSql("DROP INDEX IDX_4C3861DAA76C045 ON lelesys_plugin_news_domain_model_asset");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_asset DROP thumbnailresource, DROP iconresource, DROP carouselresource");
	}

}

?>