<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130905203427 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join DROP FOREIGN KEY FK_240954B25942C09B");
		$this->addSql("DROP INDEX IDX_240954B25942C09B ON lelesys_plugin_news_domain_model_news_files_join");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join CHANGE news_file media_document VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join ADD CONSTRAINT FK_240954B2D708A4C4 FOREIGN KEY (media_document) REFERENCES typo3_media_domain_model_document (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_240954B2D708A4C4 ON lelesys_plugin_news_domain_model_news_files_join (media_document)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join ADD PRIMARY KEY (news_news, media_document)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join DROP FOREIGN KEY FK_240954B2D708A4C4");
		$this->addSql("DROP INDEX IDX_240954B2D708A4C4 ON lelesys_plugin_news_domain_model_news_files_join");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join CHANGE media_document news_file VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join ADD CONSTRAINT FK_240954B25942C09B FOREIGN KEY (news_file) REFERENCES lelesys_plugin_news_domain_model_file (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_240954B25942C09B ON lelesys_plugin_news_domain_model_news_files_join (news_file)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_files_join ADD PRIMARY KEY (news_news, news_file)");
	}
}

?>