<?php

namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130921152357 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE lelesys_plugin_news_domain_model_user");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP INDEX UNIQ_C7BAC71546D262E0, ADD INDEX IDX_C7BAC71546D262E0 (createdby)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE lelesys_plugin_news_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, profileimage VARCHAR(40) DEFAULT NULL, gender INT NOT NULL, address VARCHAR(255) NOT NULL, phoneno VARCHAR(255) NOT NULL, createdate DATETIME NOT NULL, updateddate DATETIME NOT NULL, INDEX IDX_57FA880C2ED0FBD0 (profileimage), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_user ADD CONSTRAINT FK_57FA880C2ED0FBD0 FOREIGN KEY (profileimage) REFERENCES typo3_flow_resource_resource (persistence_object_identifier)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_user ADD CONSTRAINT FK_57FA880C47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP INDEX IDX_C7BAC71546D262E0, ADD UNIQUE INDEX UNIQ_C7BAC71546D262E0 (createdby)");
	}

}

?>