<?php

namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130921114915 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_comment ADD replyto VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_comment ADD CONSTRAINT FK_F273B4BBFBFEBB05 FOREIGN KEY (replyto) REFERENCES lelesys_plugin_news_domain_model_comment (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_F273B4BBFBFEBB05 ON lelesys_plugin_news_domain_model_comment (replyto)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP INDEX IDX_C7BAC71546D262E0, ADD UNIQUE INDEX UNIQ_C7BAC71546D262E0 (createdby)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP FOREIGN KEY FK_C7BAC71546D262E0");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news ADD CONSTRAINT FK_C7BAC71546D262E0 FOREIGN KEY (createdby) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_comment DROP FOREIGN KEY FK_F273B4BBFBFEBB05");
		$this->addSql("DROP INDEX IDX_F273B4BBFBFEBB05 ON lelesys_plugin_news_domain_model_comment");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_comment DROP replyto");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP INDEX UNIQ_C7BAC71546D262E0, ADD INDEX IDX_C7BAC71546D262E0 (createdby)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news DROP FOREIGN KEY FK_C7BAC71546D262E0");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news ADD CONSTRAINT FK_C7BAC71546D262E0 FOREIGN KEY (createdby) REFERENCES lelesys_plugin_news_domain_model_user (persistence_object_identifier)");
	}

}

?>