<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130905171047 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join DROP FOREIGN KEY FK_979727567810DD02");
		$this->addSql("DROP INDEX IDX_979727567810DD02 ON lelesys_plugin_news_domain_model_news_assets_join");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join CHANGE news_asset media_image VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join ADD CONSTRAINT FK_97972756DA24C0EE FOREIGN KEY (media_image) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_97972756DA24C0EE ON lelesys_plugin_news_domain_model_news_assets_join (media_image)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join ADD PRIMARY KEY (news_news, media_image)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join DROP FOREIGN KEY FK_97972756DA24C0EE");
		$this->addSql("DROP INDEX IDX_97972756DA24C0EE ON lelesys_plugin_news_domain_model_news_assets_join");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join CHANGE media_image news_asset VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join ADD CONSTRAINT FK_979727567810DD02 FOREIGN KEY (news_asset) REFERENCES lelesys_plugin_news_domain_model_asset (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_979727567810DD02 ON lelesys_plugin_news_domain_model_news_assets_join (news_asset)");
		$this->addSql("ALTER TABLE lelesys_plugin_news_domain_model_news_assets_join ADD PRIMARY KEY (news_news, news_asset)");
	}
}

?>